# Generated by Django 3.0.4 on 2020-04-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tags',
            field=models.ManyToManyField(to='account.Tag'),
        ),
    ]
