# Generated by Django 3.0.4 on 2020-03-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200331_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
