# Generated by Django 3.0.4 on 2020-04-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tags',
            field=models.ManyToManyField(blank=True, to='account.Tag'),
        ),
    ]
