# Generated by Django 3.0.4 on 2020-03-31 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200331_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location_latitude',
            field=models.DecimalField(decimal_places=9, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='location_latitude'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location_longitude',
            field=models.DecimalField(decimal_places=9, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)], verbose_name='location_longitude'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location_timestamp',
            field=models.DateTimeField(null=True, verbose_name='location_timestamp'),
        ),
    ]
