# Generated by Django 3.0.4 on 2020-04-14 15:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('sender', 'recipient')},
        ),
    ]
