# Generated by Django 3.0.4 on 2020-04-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_auto_20200414_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
