# Generated by Django 3.0.4 on 2020-04-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0004_tag_usertag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTag',
        ),
    ]
