# Generated by Django 3.0.4 on 2020-04-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0005_delete_usertag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
