# Generated by Django 3.0.4 on 2020-05-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200428_1851'),
        ('matcher', '0006_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='common_tags',
            field=models.ManyToManyField(to='account.Tag'),
        ),
    ]
