export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_LOADING = "GET_LOCATION_LOADING";
export const GET_LOCATION_FAILED = "GET_LOCATION_FAILED";
export const SEND_LOCATION_SUCCESS = "SEND_LOCATION_SUCCESS";